##  Plugin Information  ##
name: DispNameChanger
version: ${project.version}
description: Lets you change the display name of yourself or others.
##  Original Author     ##
author: captainawesome7
##  Contributors        ##
authors: [itsatacoshop247, Daxiongmao87, Luke Zwekii, Sammy, SniperFodder, bearbear12345, morganm]
website: http://dev.bukkit.org/server-mods/dispnamechanger/
main: me.captain.dnc.DispNameChanger
database: true
softdepend: [Spout, TagAPI]
commands:
    rename:
        aliases: newname
        description: 改变当前玩家或目标的名称.
        permission: dispname.change
        usage: |
            在名称中使用空格需要加上引号 (如 "Super Bob").
            /rename <目标> <新名字>
            /rename <新名字>
            同义词: newname
    reset:
        aliases: resetname
        description: 重置玩家的名称或目标玩家.
        permission: dispname.change
        usage: |
            /resetname [target]
            同义词: resetname
    checkname:
        aliases: [namecheck, realname, whois]
        description: 显示玩家的名字 (真名或显示名).
        permission: dispname.check
        usage: |
            /checkname <名字>
            同义词: checkname, namecheck
    displaylist:
        aliases: [listnames, displist, dnclist]
        description: 显示所有用户及其显示名称的列表.
        permission: dispname.list
        usage: |
            /displaylist [page number]
            同义词: listnames, displist, dnclist
permissions:
    dispname.*:
        description: 允许访问的所有DispNameChanger命令和保留的颜色代码.
        children:
            dispname.announce: true
            dispname.change: true
            dispname.changeother: true
            dispname.changespace: true
            dispname.check: true
            dispname.color.*: true
            dispname.list: true

    dispname.color.*:
        description: 允许访问所有的颜色代码和样式.
        children:
            dispname.color.style.*: true
            dispname.color.all: true

    dispname.color.style.*:
        description: 允许访问显示名称中使用的所有特殊样式颜色代码.
        children:
            dispname.color.style.bold: true
            dispname.color.style.italic: true
            dispname.color.style.magic: true
            dispname.color.style.strike: true
            dispname.color.style.underline: true

    dispname.color.all:
        description: 允许访问显示名称中使用的所有颜色代码.
        children:
            dispname.color.black: true
            dispname.color.darkblue: true
            dispname.color.darkgreen: true
            dispname.color.darkaqua: true
            dispname.color.darkred: true
            dispname.color.purple: true
            dispname.color.orange: true
            dispname.color.grey: true
            dispname.color.darkgrey: true
            dispname.color.indigo: true
            dispname.color.brightgreen: true
            dispname.color.aqua: true
            dispname.color.red: true
            dispname.color.pink: true
            dispname.color.yellow: true
            dispname.color.white: true
    dispname.announce:
        description: 允许用户接收名称变更广播.
        default: op
    dispname.change:
        description: 允许用户更改自己的显示名称.
        default: op
    dispname.changeother:
        description: 允许用户改变别人的显示名称.
        default: op
    dispname.changespace:
        description: 允许用户在显示名称中使用空格.
        default: op
    dispname.check:
        description: 允许用户检查改名者是谁.
        default: true
    dispname.color.style.bold:
        description: 允许用户使用 粗体 颜色代码.
        default: op
    dispname.color.style.italic:
        description: 允许用户使用 斜体 颜色代码.
        default: op
    dispname.color.style.magic:
        description: 允许用户使用 随机字符 颜色代码.
        default: op
    dispname.color.style.strike:
        description: 允许用户使用 删除线 颜色代码.
        default: op
    dispname.color.style.underline:
        description: 允许用户使用 下划线 颜色代码.
        default: op
    dispname.color.black:
        description: 允许用户使用 黑色 颜色代码.
        default: op
    dispname.color.darkblue:
        description: 允许用户使用 深蓝 颜色代码. 
        default: op
    dispname.color.darkgreen:
        description: 允许用户使用 深绿 颜色代码. 
        default: op
    dispname.color.darkaqua:
        description: 允许用户使用 深青 颜色代码. 
        default: op
    dispname.color.darkred:
        description: 允许用户使用 深红 颜色代码. 
        default: op
    dispname.color.purple:
        description: 允许用户使用 紫色 颜色代码.
        default: op
    dispname.color.orange:
        description: 允许用户使用 橙色 颜色代码. 或者说金色
        default: op
    dispname.color.grey:
        description: 允许用户使用 灰色 颜色代码. 或者说银色
        default: op
    dispname.color.darkgrey:
        description: 允许用户使用 深灰 颜色代码. 
        default: op
    dispname.color.indigo:
        description: 允许用户使用 靛青 颜色代码. 或者说蓝色
        default: op
    dispname.color.brightgreen:
        description: 允许用户使用 浅绿 颜色代码. 
        default: op
    dispname.color.aqua:
        description: 允许用户使用 青色 颜色代码.
        default: op
    dispname.color.red:
        description: 允许用户使用 红色 颜色代码.
        default: op
    dispname.color.pink:
        description: 允许用户使用 粉色 颜色代码.
        default: op
    dispname.color.yellow:
        description: 允许用户使用 黄色 颜色代码.
        default: op
    dispname.color.white:
        description: 允许用户使用 白色 颜色代码.
        default: op
    dispname.list:
        descriptions: 允许用户列出所有名字.
        default: true