##  Plugin Information  ##
name: DispNameChanger
version: 5.4.1
description: Lets you change the display name of yourself or others.
##  Original Author     ##
author: captainawesome7
##  Contributors        ##
authors: [itsatacoshop247, Daxiongmao87, Luke Zwekii, Sammy, SniperFodder]
website: http://dev.bukkit.org/server-mods/dispnamechanger/
main: me.captain.dnc.DispNameChanger
database: true
softdepend: [Spout]
commands:
    rename:
        aliases: newname
        description: Changes the name of the player or target.
        permission: dispname.change
        usage: |
            /rename <target> <new name>
            /rename <new name>
            Aliases: newname
    reset:
        aliases: resetname
        description: Resets the players name or target player.
        permission: dispname.change
        usage: |
            /resetname [target]
            Aliases: resetname
    check:
        aliases: [checkname, namecheck, realname]
        description: Shows the alternate name of the player (Real name or Display name).
        permission: dispname.check
        usage: |
            /checkname <name>
            Aliases: checkname, namecheck
permissions:
    dispname.*:
        description: Allows access to all DispNameChanger commands.
        children:
            dispname.change: true
            dispname.changeother: true
            dispname.changespace: true
            dispname.check: true
            dispname.announce: true
    dispname.change:
        description: Allows a user to change their display name.
        default: op
    dispname.changeother:
        description: Allows a user to change someone else's display name.
        default: op
    dispname.changespace:
        description: Allows a user to use a space in the display name.
        default: op
    dispname.check:
        description: Allows a user to check who a renamed person is.
        default: true
    dispname.announce:
        description: Allows a user to recieve admin only name change broadcasts.
        default: op